config/routes.rb
Rails.application.routes.draw do
root :to => 'main#index'
resources :apps
resources :android
resources :web
resources :ruby

end

app/models/app.rb
class App < ActiveRecord::Base
	
end

app/controllers/android_controller.rb
class AndroidController < ApplicationController
	def index
	 	@apps = App.all
	 	@ora_actuala = Time.now
	 	@apps_android = []
	 	@apps.each do |app|
	 		@apps_android << app if app.category.to_s[0].downcase == "a"
	 	end
	end

	def show
		@app = App.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
	def index
	 	@apps = App.all
	 	@ora_actuala = Time.now
	end

	def show
		@app = App.find(params[:id])
	end

	def edit
		@app = App.find(params[:id])
	end

	def new
		@app = App.new
	end

	def create
		@app = App.new(app_params)

		if @app.save
			redirect_to apps_path, :notice => "aplicatie salvata cu success"
		else
			render "new"
		end
	end
	
	def update
		@app = App.find(params[:id])

		if @app.update_attributes(params.require(:app).permit(:title, :description, :category, :imagelink, :imagelink2, :imagelink3, :imagelink4, :imagelink5, :applicationlink, :applicationlink2))
			redirect_to apps_path, :notice => "Editarea a avut success."
		else
			render "edit"
		end
	end

	def destroy
		@app = App.find(params[:id])
		@app.destroy

		redirect_to apps_path , :notice => "Aplicatia a fost stearsa."
	end

	private
	def app_params
		params.require(:app).permit(:title, :description, :category, :imagelink, :imagelink2, :imagelink3, :imagelink4, :imagelink5, :applicationlink, :applicationlink)
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index
		@apps = App.all
		@ora_actuala = Time.now
		#@categories = Category.all
	end
end

app/controllers/ruby_controller.rb
class RubyController < ApplicationController
	def index
	 	@apps = App.all
		@ora_actuala = Time.now
	 	@apps_ruby = []
	 	@apps.each do |app|
	 		@apps_ruby << app if app.category.to_s[0].downcase == "r"
	 	end
	end

	def show
		@app = App.find(params[:id])
	end
end

app/controllers/web_controller.rb
class WebController < ApplicationController
	def index
	 	@apps = App.all
	 	@ora_actuala = Time.now
	 	@apps_web = []
	 	@apps.each do |app|
	 		@apps_web << app if app.category.to_s[0].downcase == "w"
	 	end
	end

	def show
		@app = App.find(params[:id])
	end
end

app/helpers/android_helper.rb
module AndroidHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/ruby_helper.rb
module RubyHelper
end

app/helpers/web_helper.rb
module WebHelper
end

app/views/android/index.html.erb
<h2 class="bigtitle">Android Apps Index</h2>
<div class="container_android">
	<% @apps_android.each do |app| %>		
		<a class="wrapper_android" href="<%= android_path(app)%>"> 
		
			<h1><%= app.title %></h1>
			
			<p><%= app.description.to_s[0..50] + "..." %></p>
			
				<div class="icon_container">
				<% if app.applicationlink2 != "" %>
					<img src="<%= app.applicationlink2 %>" width="100%" height="100%">
					<% else %>
					<img src="assets/android.jpg" width="100%" height="100%">	
					<% end %>
					
				</div>
			
		</a>
	<% end %>
</div>

app/views/android/show.html.erb
<div class="container_android">

<h1 class="android_title"><%= @app.title %></h1>
<hr>

<h3><a href="<%=@app.applicationlink %>">Click for APK Download Link </a> </h3>
<h2> Descriere : </h2>
<p class="description"><%= @app.description %></p>

	


<div class="clearer"></div>
<% if @app.imagelink != ""%>
<a href="<%= @app.imagelink %>"><img src="<%= @app.imagelink%>" width="170" height="300"></a>
<% end %>
<% if @app.imagelink2 != ""%>
<a href="<%= @app.imagelink2 %>"><img src="<%= @app.imagelink2%>" width="170" height="300"></a>
<% end %>
<% if @app.imagelink3 != ""%>
<a href="<%= @app.imagelink3 %>"><img src="<%= @app.imagelink3%>" width="170" height="300"></a>
<% end %>
<% if @app.imagelink4 != ""%>
<a href="<%= @app.imagelink4 %>"><img src="<%= @app.imagelink4%>" width="170" height="300"></a>
<% end %>
<% if @app.imagelink5 != ""%>
<a href="<%= @app.imagelink5 %>"><img src="<%= @app.imagelink5%>" width="170" height="300"></a>
<% end %>



<hr>
<small>Adaugat la: <%= @app.created_at %></small>
</div>

app/views/apps/edit.html.erb
<div id="centrare">
<h1>Editeaza datele aplicatiei</h1>

<%= form_for @app do |f| %>
	<% if @app.errors.any? %>
	<h2>Errors:</h2>
	<ul>
		<% @app.errors.full_messages.each do |message|%>
		
		<li><%= message %></li>

		<% end %>	
	</ul>
	<% end %>

<p>
	<%= f.label :title %><br />
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :category %><br />
	<%= f.text_field :category %>
</p>
<p>
	<%= f.label :imagelink %><br />
	<%= f.text_area :imagelink %>
</p>
<p>
	<%= f.label :imagelink2 %><br />
	<%= f.text_area :imagelink2 %>
</p>
<p>
	<%= f.label :imagelink3 %><br />
	<%= f.text_area :imagelink3 %>
</p>
<p>
	<%= f.label :imagelink4 %><br />
	<%= f.text_area :imagelink4 %>
</p>
<p>
	<%= f.label :imagelink5 %><br />
	<%= f.text_area :imagelink5 %>
</p>
<p>
	<%= f.label :applicationlink %><br />
	<%= f.text_area :applicationlink %>
</p>
<p>
	<%= f.label :applicationlink2 %><br />
	<%= f.text_area :applicationlink2 %>
</p>
<p>
	<%= f.label :description %><br />
	<%= f.text_area :description %>
</p>
	<p>
		<%= f.submit "Salveaza Editarea"%>
	</p>
<% end %>

</div>

app/views/apps/index.html.erb
<h1>All Apps Index</h1>

	<% @apps.each do |app| %>
		<div class="wrapper">
			<h1><%= link_to app.title, app_path(app) %></h1>
			<!-- <p>Category: <%= app.category%></p> -->
			<p>Description: <%= app.description.to_s[0..30] + "..." %></p>
			<!-- <p>Imagelink: <%= app.imagelink%></p>
			<p>app_link: <%= app.applicationlink%></p> -->
			<%= link_to "Editeaza", edit_app_path(app) %> |
			<%= link_to "Sterge", app, :method => :delete, :confirm => "Sunteti Sigur?"  %> 
		</div>




	<% end %>
	<div class="clearer"></div>
	<br>

	<div id="addapp"><%= link_to "Adauga Aplicatie", new_app_path %></div>

<h2>Current Time is : <%= @ora_actuala %></h2>

app/views/apps/new.html.erb
<div id="centrare">
<h1>Introdu Aplicatie Noua</h1>

<%= form_for @app do |f| %>
	<% if @app.errors.any? %>
	<h2>Errors:</h2>
	<ul>
		<% @app.errors.full_messages.each do |message|%>
		
		<li><%= message %></li>

		<% end %>	
	</ul>
	<% end %>

<p>
	<%= f.label :title %><br />
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :category %><br />
	<%= f.text_field :category %>
</p>
<p>
	<%= f.label :imagelink %><br />
	<%= f.text_area :imagelink %>
</p>
<p>
	<%= f.label :imagelink2 %><br />
	<%= f.text_area :imagelink2 %>
</p>
<p>
	<%= f.label :imagelink3 %><br />
	<%= f.text_area :imagelink3 %>
</p>
<p>
	<%= f.label :imagelink4 %><br />
	<%= f.text_area :imagelink4 %>
</p>
<p>
	<%= f.label :imagelink5 %><br />
	<%= f.text_area :imagelink5 %>
</p>
<p>
	<%= f.label :applicationlink %><br />
	<%= f.text_area :applicationlink %>
</p>
<p>
	<%= f.label :applicationlink2 %><br />
	<%= f.text_area :applicationlink2 %>
</p>
<p>
	<%= f.label :description %><br />
	<%= f.text_area :description %>
</p>
	<p>
		<%= f.submit "Adauga Client"%>
	</p>
<% end %>

</div>

app/views/apps/show.html.erb
<h1><%= @app.title %></h1>
<p>categoria : <%= @app.category %></p>
<p>linkimagine : <%= @app.imagelink %></p>
<p>linkimagine2 : <%= @app.imagelink2 %></p>
<p>linkimagine3 : <%= @app.imagelink3 %></p>
<p>linkimagine4 : <%= @app.imagelink4 %></p>
<p>linkimagine5 : <%= @app.imagelink5 %></p>
<p>linkaplicatie : <%= @app.applicationlink %></p>
<p>linkaplicatie2 : <%= @app.applicationlink2 %></p>
<p>descrierea : <%= @app.description %></p>

<small>Adaugat la: <%= @app.created_at %></small>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h2 class="bigtitle">PBC PORTFOLIO</h2>

<!--For each category type , display an round SQUARE ! -->

<div class="category_container">
	
	<a href="/android"><div class="category" id="cat1"></div></a>
	<a href="/web"><div class="category" id="cat2"></div></a>
	<a href="/ruby"><div class="category" id="cat3"></div></a>
	<!--
	<div class="category" id="cat4">4 Other kind of programming</div>
	<div class="category" id="">5</div>
	<div class="category" id="">6</div>
	-->
</div>
<div class="clearer"></div>
<h3>Recommended view-ing resolution 1920x1080 (full hd) </h3>
<h5>Current Time is : <%= @ora_actuala %></h5>

app/views/ruby/index.html.erb
<h2 class="bigtitle">Ruby Apps/Scripts Index</h2>
<div class="container_ruby">
	<% @apps_ruby.each do |app| %>
		<a class="wrapper_ruby" href="<%=  ruby_path(app) %>">
			
			<h1><%= app.title %></h1>
		
			<p><%= app.description.to_s[0..50] + "..." %></p>
			
				<div class="icon_container">
					<img src="assets/rails.jpg" width="100%" height="100%">	
				</div>

		</a>
	<% end %>
</div>

app/views/ruby/show.html.erb
<div class="container_android">

<h1 class="ruby_title"><%= @app.title %></h1>
<hr>

<!-- <h3><a href="<%=@app.applicationlink %>">Click for APK Download Link </a> </h3> -->
<h2> Descriere : </h2>
<p class="description"><%= @app.description %></p>

	






<div class="clearer"></div>
<% if @app.imagelink != ""%>
<img src="<%= @apps.imagelink%>" width="170" height="300">
<% end %>
<% if @app.imagelink2 != ""%>
<img src="<%= @apps.imagelink2%>" width="170" height="300">
<% end %>
<% if @app.imagelink3 != ""%>
<img src="<%= @apps.imagelink3%>" width="170" height="300">
<% end %>
<% if @app.imagelink4 != ""%>
<img src="<%= @apps.imagelink4%>" width="170" height="300">
<% end %>
<% if @app.imagelink5 != ""%>
<img src="<%= @apps.imagelink5%>" width="170" height="300">
<% end %>


</div>

app/views/web/index.html.erb
<h2 class="bigtitle">Web Apps Index</h2>
<div class="container_android">
	<% @apps_web.each do |app| %>
		<a class="wrapper_web" href="<%= web_path(app) %>">

			<h1><%= app.title%></h1>
			
			<p><%= app.description.to_s[0..50] + "..." %></p>
			
				<div class="icon_container">
					<% if app.applicationlink2 != "" %>
					<img src="<%= app.applicationlink2 %>" width="100%" height="100%">
					<% else %>
					<img src="assets/web.jpg" width="100%" height="100%">	
					<% end %>
				</div>
		</a>

	<% end %>
	</div>

app/views/web/show.html.erb
<div class="container_web">

<h1 class="web_title"><%= @app.title %></h1>
<hr>

<h3><a href="<%=@app.applicationlink %>">Click to visit the site. </a> </h3>
<h2> Descriere : </h2>
<p class="description"><%= @app.description %></p>

<p class="">Previzualizare rapida:</p>
<iframe src="<%= @app.applicationlink %>" width="1000" height="500"></iframe>



<!-- <div class="imagini">

	<div class="imagine"></div>
	<div class="imagine"></div>

</div> -->
<div class="clearer"></div>

<!-- <p>linkimagine : <%= @app.imagelink %></p>
<p>linkaplicatie : <%= @app.applicationlink %></p>
<hr> -->
<small>Adaugat la: <%= @app.created_at %></small>
</div>

<!-- 
<h3> Plus an iframe !!!</h3> -->